# @package _global_

#### Model params #############################################################
model:
  name: enhanced_rnn
  hparams:
    hidden_size: 128
    emb_size: 32
    rnn_layers: 2
    dropout: 0.2

