defaults:
  - _self_
  - dataset: wind
  - model: tts_imp
  - lr_scheduler: multistep

#### Experiment params ########################################################
hydra:
  run:
    dir: logs/${dataset.name}/${model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

experiment_name: peakweather_wind
mlflow_tracking_uri: null

workers: 0
num_threads: 1

#### Training params ##########################################################
epochs: 200
patience: 40
batch_size: 32
train_batches: 300  # 1.0
grad_clip_val: 5

loss_fn: ens

sampling:
  mc_samples_train: 16
  mc_samples_eval: 11
  mc_samples_test: 100

optimizer:
  name: Adam
  hparams:
    lr: 0.001

nwp_test_set: False
load_model_path: null
