defaults:
  - _self_
  - dataset: temperature
  - model: tcn
  - lr_scheduler: multistep

#### Experiment params ########################################################
hydra:
  run:
    dir: logs/${dataset.name}/${model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

experiment_name: peakweather_temperature
mlflow_tracking_uri: null

seed: null

workers: 4

#### Training params ##########################################################
epochs: 120
patience: 25
batch_size: 16  # Physical batch size per GPU
accumulate_grad_batches: 2  # Effective batch size = batch_size * accumulate_grad_batches = 32
grad_clip_val: 5

loss_fn: ens  

sampling:
  mc_samples_train: 16
  mc_samples_eval: 11
  mc_samples_test: 100

scaler:
  method: Standard
  axis: global
  scale_target: true

optimizer:
  name: Adam
  hparams:
    lr: 0.001
    weight_decay: 0.0001

load_model_path: null
